// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: app/order/cmd/rpc/pb/order.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HomestayOrder struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Sn                  string                 `protobuf:"bytes,2,opt,name=sn,proto3" json:"sn"`
	UserId              int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id"`
	HomestayId          int64                  `protobuf:"varint,4,opt,name=homestay_id,json=homestayId,proto3" json:"homestay_id"`
	Title               string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title"`
	SubTitle            string                 `protobuf:"bytes,6,opt,name=sub_title,json=subTitle,proto3" json:"sub_title"`
	Cover               string                 `protobuf:"bytes,7,opt,name=cover,proto3" json:"cover"`
	Info                string                 `protobuf:"bytes,8,opt,name=info,proto3" json:"info"`
	PeopleNum           int64                  `protobuf:"varint,9,opt,name=people_num,json=peopleNum,proto3" json:"people_num"`
	RowType             int64                  `protobuf:"varint,10,opt,name=row_type,json=rowType,proto3" json:"row_type"`
	FoodInfo            string                 `protobuf:"bytes,11,opt,name=food_info,json=foodInfo,proto3" json:"food_info"`
	FoodPrice           int64                  `protobuf:"varint,12,opt,name=food_price,json=foodPrice,proto3" json:"food_price"`
	HomestayPrice       int64                  `protobuf:"varint,13,opt,name=homestay_price,json=homestayPrice,proto3" json:"homestay_price"`
	MarketHomestayPrice int64                  `protobuf:"varint,14,opt,name=market_homestay_price,json=marketHomestayPrice,proto3" json:"market_homestay_price"`
	HomestayBusinessId  int64                  `protobuf:"varint,15,opt,name=homestay_business_id,json=homestayBusinessId,proto3" json:"homestay_business_id"`
	HomestayUserId      int64                  `protobuf:"varint,16,opt,name=homestay_user_id,json=homestayUserId,proto3" json:"homestay_user_id"`
	LiveStartDate       int64                  `protobuf:"varint,17,opt,name=live_start_date,json=liveStartDate,proto3" json:"live_start_date"`
	LiveEndDate         int64                  `protobuf:"varint,18,opt,name=live_end_date,json=liveEndDate,proto3" json:"live_end_date"`
	LivePeopleNum       int64                  `protobuf:"varint,19,opt,name=live_people_num,json=livePeopleNum,proto3" json:"live_people_num"`
	TradeState          int64                  `protobuf:"varint,20,opt,name=trade_state,json=tradeState,proto3" json:"trade_state"`
	TradeCode           string                 `protobuf:"bytes,21,opt,name=trade_code,json=tradeCode,proto3" json:"trade_code"`
	Remark              string                 `protobuf:"bytes,22,opt,name=remark,proto3" json:"remark"`
	OrderTotalPrice     int64                  `protobuf:"varint,23,opt,name=order_total_price,json=orderTotalPrice,proto3" json:"order_total_price"`
	FoodTotalPrice      int64                  `protobuf:"varint,24,opt,name=food_total_price,json=foodTotalPrice,proto3" json:"food_total_price"`
	HomestayTotalPrice  int64                  `protobuf:"varint,25,opt,name=homestay_total_price,json=homestayTotalPrice,proto3" json:"homestay_total_price"`
	CreateTime          int64                  `protobuf:"varint,26,opt,name=create_time,json=createTime,proto3" json:"create_time"`
	NeedFood            int64                  `protobuf:"varint,27,opt,name=need_food,json=needFood,proto3" json:"need_food"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *HomestayOrder) Reset() {
	*x = HomestayOrder{}
	mi := &file_app_order_cmd_rpc_pb_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HomestayOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HomestayOrder) ProtoMessage() {}

func (x *HomestayOrder) ProtoReflect() protoreflect.Message {
	mi := &file_app_order_cmd_rpc_pb_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HomestayOrder.ProtoReflect.Descriptor instead.
func (*HomestayOrder) Descriptor() ([]byte, []int) {
	return file_app_order_cmd_rpc_pb_order_proto_rawDescGZIP(), []int{0}
}

func (x *HomestayOrder) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *HomestayOrder) GetSn() string {
	if x != nil {
		return x.Sn
	}
	return ""
}

func (x *HomestayOrder) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *HomestayOrder) GetHomestayId() int64 {
	if x != nil {
		return x.HomestayId
	}
	return 0
}

func (x *HomestayOrder) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *HomestayOrder) GetSubTitle() string {
	if x != nil {
		return x.SubTitle
	}
	return ""
}

func (x *HomestayOrder) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *HomestayOrder) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

func (x *HomestayOrder) GetPeopleNum() int64 {
	if x != nil {
		return x.PeopleNum
	}
	return 0
}

func (x *HomestayOrder) GetRowType() int64 {
	if x != nil {
		return x.RowType
	}
	return 0
}

func (x *HomestayOrder) GetFoodInfo() string {
	if x != nil {
		return x.FoodInfo
	}
	return ""
}

func (x *HomestayOrder) GetFoodPrice() int64 {
	if x != nil {
		return x.FoodPrice
	}
	return 0
}

func (x *HomestayOrder) GetHomestayPrice() int64 {
	if x != nil {
		return x.HomestayPrice
	}
	return 0
}

func (x *HomestayOrder) GetMarketHomestayPrice() int64 {
	if x != nil {
		return x.MarketHomestayPrice
	}
	return 0
}

func (x *HomestayOrder) GetHomestayBusinessId() int64 {
	if x != nil {
		return x.HomestayBusinessId
	}
	return 0
}

func (x *HomestayOrder) GetHomestayUserId() int64 {
	if x != nil {
		return x.HomestayUserId
	}
	return 0
}

func (x *HomestayOrder) GetLiveStartDate() int64 {
	if x != nil {
		return x.LiveStartDate
	}
	return 0
}

func (x *HomestayOrder) GetLiveEndDate() int64 {
	if x != nil {
		return x.LiveEndDate
	}
	return 0
}

func (x *HomestayOrder) GetLivePeopleNum() int64 {
	if x != nil {
		return x.LivePeopleNum
	}
	return 0
}

func (x *HomestayOrder) GetTradeState() int64 {
	if x != nil {
		return x.TradeState
	}
	return 0
}

func (x *HomestayOrder) GetTradeCode() string {
	if x != nil {
		return x.TradeCode
	}
	return ""
}

func (x *HomestayOrder) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *HomestayOrder) GetOrderTotalPrice() int64 {
	if x != nil {
		return x.OrderTotalPrice
	}
	return 0
}

func (x *HomestayOrder) GetFoodTotalPrice() int64 {
	if x != nil {
		return x.FoodTotalPrice
	}
	return 0
}

func (x *HomestayOrder) GetHomestayTotalPrice() int64 {
	if x != nil {
		return x.HomestayTotalPrice
	}
	return 0
}

func (x *HomestayOrder) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *HomestayOrder) GetNeedFood() int64 {
	if x != nil {
		return x.NeedFood
	}
	return 0
}

type CreateHomestayOrderRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	HomestayId      int64                  `protobuf:"varint,1,opt,name=homestay_id,json=homestayId,proto3" json:"homestay_id"`
	IsFood          bool                   `protobuf:"varint,2,opt,name=is_food,json=isFood,proto3" json:"is_food"`
	LiveStartDate   int64                  `protobuf:"varint,3,opt,name=live_start_date,json=liveStartDate,proto3" json:"live_start_date"`
	LiveEndDate     int64                  `protobuf:"varint,4,opt,name=live_end_date,json=liveEndDate,proto3" json:"live_end_date"`
	UserId          int64                  `protobuf:"varint,5,opt,name=user_id,json=userId,proto3" json:"user_id"`
	LivePeopleCount int64                  `protobuf:"varint,6,opt,name=live_people_count,json=livePeopleCount,proto3" json:"live_people_count"`
	Remark          string                 `protobuf:"bytes,7,opt,name=remark,proto3" json:"remark"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateHomestayOrderRequest) Reset() {
	*x = CreateHomestayOrderRequest{}
	mi := &file_app_order_cmd_rpc_pb_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHomestayOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHomestayOrderRequest) ProtoMessage() {}

func (x *CreateHomestayOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_order_cmd_rpc_pb_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHomestayOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateHomestayOrderRequest) Descriptor() ([]byte, []int) {
	return file_app_order_cmd_rpc_pb_order_proto_rawDescGZIP(), []int{1}
}

func (x *CreateHomestayOrderRequest) GetHomestayId() int64 {
	if x != nil {
		return x.HomestayId
	}
	return 0
}

func (x *CreateHomestayOrderRequest) GetIsFood() bool {
	if x != nil {
		return x.IsFood
	}
	return false
}

func (x *CreateHomestayOrderRequest) GetLiveStartDate() int64 {
	if x != nil {
		return x.LiveStartDate
	}
	return 0
}

func (x *CreateHomestayOrderRequest) GetLiveEndDate() int64 {
	if x != nil {
		return x.LiveEndDate
	}
	return 0
}

func (x *CreateHomestayOrderRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateHomestayOrderRequest) GetLivePeopleCount() int64 {
	if x != nil {
		return x.LivePeopleCount
	}
	return 0
}

func (x *CreateHomestayOrderRequest) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

type CreateHomestayOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sn            string                 `protobuf:"bytes,1,opt,name=sn,proto3" json:"sn"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateHomestayOrderResponse) Reset() {
	*x = CreateHomestayOrderResponse{}
	mi := &file_app_order_cmd_rpc_pb_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHomestayOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHomestayOrderResponse) ProtoMessage() {}

func (x *CreateHomestayOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_order_cmd_rpc_pb_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHomestayOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateHomestayOrderResponse) Descriptor() ([]byte, []int) {
	return file_app_order_cmd_rpc_pb_order_proto_rawDescGZIP(), []int{2}
}

func (x *CreateHomestayOrderResponse) GetSn() string {
	if x != nil {
		return x.Sn
	}
	return ""
}

type HomestayOrderDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sn            string                 `protobuf:"bytes,1,opt,name=sn,proto3" json:"sn"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HomestayOrderDetailRequest) Reset() {
	*x = HomestayOrderDetailRequest{}
	mi := &file_app_order_cmd_rpc_pb_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HomestayOrderDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HomestayOrderDetailRequest) ProtoMessage() {}

func (x *HomestayOrderDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_order_cmd_rpc_pb_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HomestayOrderDetailRequest.ProtoReflect.Descriptor instead.
func (*HomestayOrderDetailRequest) Descriptor() ([]byte, []int) {
	return file_app_order_cmd_rpc_pb_order_proto_rawDescGZIP(), []int{3}
}

func (x *HomestayOrderDetailRequest) GetSn() string {
	if x != nil {
		return x.Sn
	}
	return ""
}

type HomestayOrderDetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HomestayOrder *HomestayOrder         `protobuf:"bytes,1,opt,name=homestay_order,json=homestayOrder,proto3" json:"homestay_order"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HomestayOrderDetailResponse) Reset() {
	*x = HomestayOrderDetailResponse{}
	mi := &file_app_order_cmd_rpc_pb_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HomestayOrderDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HomestayOrderDetailResponse) ProtoMessage() {}

func (x *HomestayOrderDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_order_cmd_rpc_pb_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HomestayOrderDetailResponse.ProtoReflect.Descriptor instead.
func (*HomestayOrderDetailResponse) Descriptor() ([]byte, []int) {
	return file_app_order_cmd_rpc_pb_order_proto_rawDescGZIP(), []int{4}
}

func (x *HomestayOrderDetailResponse) GetHomestayOrder() *HomestayOrder {
	if x != nil {
		return x.HomestayOrder
	}
	return nil
}

type UpdateHomestayOrderTradeStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sn            string                 `protobuf:"bytes,1,opt,name=sn,proto3" json:"sn"`
	TradeState    int64                  `protobuf:"varint,2,opt,name=trade_state,json=tradeState,proto3" json:"trade_state"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateHomestayOrderTradeStateRequest) Reset() {
	*x = UpdateHomestayOrderTradeStateRequest{}
	mi := &file_app_order_cmd_rpc_pb_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateHomestayOrderTradeStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateHomestayOrderTradeStateRequest) ProtoMessage() {}

func (x *UpdateHomestayOrderTradeStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_order_cmd_rpc_pb_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateHomestayOrderTradeStateRequest.ProtoReflect.Descriptor instead.
func (*UpdateHomestayOrderTradeStateRequest) Descriptor() ([]byte, []int) {
	return file_app_order_cmd_rpc_pb_order_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateHomestayOrderTradeStateRequest) GetSn() string {
	if x != nil {
		return x.Sn
	}
	return ""
}

func (x *UpdateHomestayOrderTradeStateRequest) GetTradeState() int64 {
	if x != nil {
		return x.TradeState
	}
	return 0
}

type UpdateHomestayOrderTradeStateResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	UserId          int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id"`
	Sn              string                 `protobuf:"bytes,3,opt,name=sn,proto3" json:"sn"`
	TradeCode       string                 `protobuf:"bytes,4,opt,name=trade_code,json=tradeCode,proto3" json:"trade_code"`
	LiveStartDate   int64                  `protobuf:"varint,5,opt,name=live_start_date,json=liveStartDate,proto3" json:"live_start_date"`
	LiveEndDate     int64                  `protobuf:"varint,6,opt,name=live_end_date,json=liveEndDate,proto3" json:"live_end_date"`
	OrderTotalPrice int64                  `protobuf:"varint,7,opt,name=order_total_price,json=orderTotalPrice,proto3" json:"order_total_price"`
	Title           string                 `protobuf:"bytes,8,opt,name=title,proto3" json:"title"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateHomestayOrderTradeStateResponse) Reset() {
	*x = UpdateHomestayOrderTradeStateResponse{}
	mi := &file_app_order_cmd_rpc_pb_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateHomestayOrderTradeStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateHomestayOrderTradeStateResponse) ProtoMessage() {}

func (x *UpdateHomestayOrderTradeStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_order_cmd_rpc_pb_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateHomestayOrderTradeStateResponse.ProtoReflect.Descriptor instead.
func (*UpdateHomestayOrderTradeStateResponse) Descriptor() ([]byte, []int) {
	return file_app_order_cmd_rpc_pb_order_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateHomestayOrderTradeStateResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateHomestayOrderTradeStateResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateHomestayOrderTradeStateResponse) GetSn() string {
	if x != nil {
		return x.Sn
	}
	return ""
}

func (x *UpdateHomestayOrderTradeStateResponse) GetTradeCode() string {
	if x != nil {
		return x.TradeCode
	}
	return ""
}

func (x *UpdateHomestayOrderTradeStateResponse) GetLiveStartDate() int64 {
	if x != nil {
		return x.LiveStartDate
	}
	return 0
}

func (x *UpdateHomestayOrderTradeStateResponse) GetLiveEndDate() int64 {
	if x != nil {
		return x.LiveEndDate
	}
	return 0
}

func (x *UpdateHomestayOrderTradeStateResponse) GetOrderTotalPrice() int64 {
	if x != nil {
		return x.OrderTotalPrice
	}
	return 0
}

func (x *UpdateHomestayOrderTradeStateResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type UserHomestayOrderListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LastId        int64                  `protobuf:"varint,1,opt,name=last_id,json=lastId,proto3" json:"last_id"`
	PageSize      int64                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id"`
	TradeState    int64                  `protobuf:"varint,4,opt,name=trade_state,json=tradeState,proto3" json:"trade_state"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserHomestayOrderListRequest) Reset() {
	*x = UserHomestayOrderListRequest{}
	mi := &file_app_order_cmd_rpc_pb_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserHomestayOrderListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserHomestayOrderListRequest) ProtoMessage() {}

func (x *UserHomestayOrderListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_order_cmd_rpc_pb_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserHomestayOrderListRequest.ProtoReflect.Descriptor instead.
func (*UserHomestayOrderListRequest) Descriptor() ([]byte, []int) {
	return file_app_order_cmd_rpc_pb_order_proto_rawDescGZIP(), []int{7}
}

func (x *UserHomestayOrderListRequest) GetLastId() int64 {
	if x != nil {
		return x.LastId
	}
	return 0
}

func (x *UserHomestayOrderListRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *UserHomestayOrderListRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserHomestayOrderListRequest) GetTradeState() int64 {
	if x != nil {
		return x.TradeState
	}
	return 0
}

type UserHomestayOrderListResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	HomestayOrders []*HomestayOrder       `protobuf:"bytes,1,rep,name=homestay_orders,json=homestayOrders,proto3" json:"homestay_orders"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserHomestayOrderListResponse) Reset() {
	*x = UserHomestayOrderListResponse{}
	mi := &file_app_order_cmd_rpc_pb_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserHomestayOrderListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserHomestayOrderListResponse) ProtoMessage() {}

func (x *UserHomestayOrderListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_order_cmd_rpc_pb_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserHomestayOrderListResponse.ProtoReflect.Descriptor instead.
func (*UserHomestayOrderListResponse) Descriptor() ([]byte, []int) {
	return file_app_order_cmd_rpc_pb_order_proto_rawDescGZIP(), []int{8}
}

func (x *UserHomestayOrderListResponse) GetHomestayOrders() []*HomestayOrder {
	if x != nil {
		return x.HomestayOrders
	}
	return nil
}

var File_app_order_cmd_rpc_pb_order_proto protoreflect.FileDescriptor

const file_app_order_cmd_rpc_pb_order_proto_rawDesc = "" +
	"\n" +
	" app/order/cmd/rpc/pb/order.proto\x12\x02pb\"\x85\a\n" +
	"\rHomestayOrder\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x0e\n" +
	"\x02sn\x18\x02 \x01(\tR\x02sn\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vhomestay_id\x18\x04 \x01(\x03R\n" +
	"homestayId\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12\x1b\n" +
	"\tsub_title\x18\x06 \x01(\tR\bsubTitle\x12\x14\n" +
	"\x05cover\x18\a \x01(\tR\x05cover\x12\x12\n" +
	"\x04info\x18\b \x01(\tR\x04info\x12\x1d\n" +
	"\n" +
	"people_num\x18\t \x01(\x03R\tpeopleNum\x12\x19\n" +
	"\brow_type\x18\n" +
	" \x01(\x03R\arowType\x12\x1b\n" +
	"\tfood_info\x18\v \x01(\tR\bfoodInfo\x12\x1d\n" +
	"\n" +
	"food_price\x18\f \x01(\x03R\tfoodPrice\x12%\n" +
	"\x0ehomestay_price\x18\r \x01(\x03R\rhomestayPrice\x122\n" +
	"\x15market_homestay_price\x18\x0e \x01(\x03R\x13marketHomestayPrice\x120\n" +
	"\x14homestay_business_id\x18\x0f \x01(\x03R\x12homestayBusinessId\x12(\n" +
	"\x10homestay_user_id\x18\x10 \x01(\x03R\x0ehomestayUserId\x12&\n" +
	"\x0flive_start_date\x18\x11 \x01(\x03R\rliveStartDate\x12\"\n" +
	"\rlive_end_date\x18\x12 \x01(\x03R\vliveEndDate\x12&\n" +
	"\x0flive_people_num\x18\x13 \x01(\x03R\rlivePeopleNum\x12\x1f\n" +
	"\vtrade_state\x18\x14 \x01(\x03R\n" +
	"tradeState\x12\x1d\n" +
	"\n" +
	"trade_code\x18\x15 \x01(\tR\ttradeCode\x12\x16\n" +
	"\x06remark\x18\x16 \x01(\tR\x06remark\x12*\n" +
	"\x11order_total_price\x18\x17 \x01(\x03R\x0forderTotalPrice\x12(\n" +
	"\x10food_total_price\x18\x18 \x01(\x03R\x0efoodTotalPrice\x120\n" +
	"\x14homestay_total_price\x18\x19 \x01(\x03R\x12homestayTotalPrice\x12\x1f\n" +
	"\vcreate_time\x18\x1a \x01(\x03R\n" +
	"createTime\x12\x1b\n" +
	"\tneed_food\x18\x1b \x01(\x03R\bneedFood\"\xff\x01\n" +
	"\x1aCreateHomestayOrderRequest\x12\x1f\n" +
	"\vhomestay_id\x18\x01 \x01(\x03R\n" +
	"homestayId\x12\x17\n" +
	"\ais_food\x18\x02 \x01(\bR\x06isFood\x12&\n" +
	"\x0flive_start_date\x18\x03 \x01(\x03R\rliveStartDate\x12\"\n" +
	"\rlive_end_date\x18\x04 \x01(\x03R\vliveEndDate\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\x03R\x06userId\x12*\n" +
	"\x11live_people_count\x18\x06 \x01(\x03R\x0flivePeopleCount\x12\x16\n" +
	"\x06remark\x18\a \x01(\tR\x06remark\"-\n" +
	"\x1bCreateHomestayOrderResponse\x12\x0e\n" +
	"\x02sn\x18\x01 \x01(\tR\x02sn\",\n" +
	"\x1aHomestayOrderDetailRequest\x12\x0e\n" +
	"\x02sn\x18\x01 \x01(\tR\x02sn\"W\n" +
	"\x1bHomestayOrderDetailResponse\x128\n" +
	"\x0ehomestay_order\x18\x01 \x01(\v2\x11.pb.HomestayOrderR\rhomestayOrder\"W\n" +
	"$UpdateHomestayOrderTradeStateRequest\x12\x0e\n" +
	"\x02sn\x18\x01 \x01(\tR\x02sn\x12\x1f\n" +
	"\vtrade_state\x18\x02 \x01(\x03R\n" +
	"tradeState\"\x8d\x02\n" +
	"%UpdateHomestayOrderTradeStateResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x0e\n" +
	"\x02sn\x18\x03 \x01(\tR\x02sn\x12\x1d\n" +
	"\n" +
	"trade_code\x18\x04 \x01(\tR\ttradeCode\x12&\n" +
	"\x0flive_start_date\x18\x05 \x01(\x03R\rliveStartDate\x12\"\n" +
	"\rlive_end_date\x18\x06 \x01(\x03R\vliveEndDate\x12*\n" +
	"\x11order_total_price\x18\a \x01(\x03R\x0forderTotalPrice\x12\x14\n" +
	"\x05title\x18\b \x01(\tR\x05title\"\x8e\x01\n" +
	"\x1cUserHomestayOrderListRequest\x12\x17\n" +
	"\alast_id\x18\x01 \x01(\x03R\x06lastId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vtrade_state\x18\x04 \x01(\x03R\n" +
	"tradeState\"[\n" +
	"\x1dUserHomestayOrderListResponse\x12:\n" +
	"\x0fhomestay_orders\x18\x01 \x03(\v2\x11.pb.HomestayOrderR\x0ehomestayOrders2\x92\x03\n" +
	"\fOrderService\x12V\n" +
	"\x13CreateHomestayOrder\x12\x1e.pb.CreateHomestayOrderRequest\x1a\x1f.pb.CreateHomestayOrderResponse\x12V\n" +
	"\x13HomestayOrderDetail\x12\x1e.pb.HomestayOrderDetailRequest\x1a\x1f.pb.HomestayOrderDetailResponse\x12t\n" +
	"\x1dUpdateHomestayOrderTradeState\x12(.pb.UpdateHomestayOrderTradeStateRequest\x1a).pb.UpdateHomestayOrderTradeStateResponse\x12\\\n" +
	"\x15UserHomestayOrderList\x12 .pb.UserHomestayOrderListRequest\x1a!.pb.UserHomestayOrderListResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_app_order_cmd_rpc_pb_order_proto_rawDescOnce sync.Once
	file_app_order_cmd_rpc_pb_order_proto_rawDescData []byte
)

func file_app_order_cmd_rpc_pb_order_proto_rawDescGZIP() []byte {
	file_app_order_cmd_rpc_pb_order_proto_rawDescOnce.Do(func() {
		file_app_order_cmd_rpc_pb_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_order_cmd_rpc_pb_order_proto_rawDesc), len(file_app_order_cmd_rpc_pb_order_proto_rawDesc)))
	})
	return file_app_order_cmd_rpc_pb_order_proto_rawDescData
}

var file_app_order_cmd_rpc_pb_order_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_app_order_cmd_rpc_pb_order_proto_goTypes = []any{
	(*HomestayOrder)(nil),                         // 0: pb.HomestayOrder
	(*CreateHomestayOrderRequest)(nil),            // 1: pb.CreateHomestayOrderRequest
	(*CreateHomestayOrderResponse)(nil),           // 2: pb.CreateHomestayOrderResponse
	(*HomestayOrderDetailRequest)(nil),            // 3: pb.HomestayOrderDetailRequest
	(*HomestayOrderDetailResponse)(nil),           // 4: pb.HomestayOrderDetailResponse
	(*UpdateHomestayOrderTradeStateRequest)(nil),  // 5: pb.UpdateHomestayOrderTradeStateRequest
	(*UpdateHomestayOrderTradeStateResponse)(nil), // 6: pb.UpdateHomestayOrderTradeStateResponse
	(*UserHomestayOrderListRequest)(nil),          // 7: pb.UserHomestayOrderListRequest
	(*UserHomestayOrderListResponse)(nil),         // 8: pb.UserHomestayOrderListResponse
}
var file_app_order_cmd_rpc_pb_order_proto_depIdxs = []int32{
	0, // 0: pb.HomestayOrderDetailResponse.homestay_order:type_name -> pb.HomestayOrder
	0, // 1: pb.UserHomestayOrderListResponse.homestay_orders:type_name -> pb.HomestayOrder
	1, // 2: pb.OrderService.CreateHomestayOrder:input_type -> pb.CreateHomestayOrderRequest
	3, // 3: pb.OrderService.HomestayOrderDetail:input_type -> pb.HomestayOrderDetailRequest
	5, // 4: pb.OrderService.UpdateHomestayOrderTradeState:input_type -> pb.UpdateHomestayOrderTradeStateRequest
	7, // 5: pb.OrderService.UserHomestayOrderList:input_type -> pb.UserHomestayOrderListRequest
	2, // 6: pb.OrderService.CreateHomestayOrder:output_type -> pb.CreateHomestayOrderResponse
	4, // 7: pb.OrderService.HomestayOrderDetail:output_type -> pb.HomestayOrderDetailResponse
	6, // 8: pb.OrderService.UpdateHomestayOrderTradeState:output_type -> pb.UpdateHomestayOrderTradeStateResponse
	8, // 9: pb.OrderService.UserHomestayOrderList:output_type -> pb.UserHomestayOrderListResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_app_order_cmd_rpc_pb_order_proto_init() }
func file_app_order_cmd_rpc_pb_order_proto_init() {
	if File_app_order_cmd_rpc_pb_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_order_cmd_rpc_pb_order_proto_rawDesc), len(file_app_order_cmd_rpc_pb_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_order_cmd_rpc_pb_order_proto_goTypes,
		DependencyIndexes: file_app_order_cmd_rpc_pb_order_proto_depIdxs,
		MessageInfos:      file_app_order_cmd_rpc_pb_order_proto_msgTypes,
	}.Build()
	File_app_order_cmd_rpc_pb_order_proto = out.File
	file_app_order_cmd_rpc_pb_order_proto_goTypes = nil
	file_app_order_cmd_rpc_pb_order_proto_depIdxs = nil
}
