// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: travel.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Homestay struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Title               string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title"`
	SubTitle            string                 `protobuf:"bytes,3,opt,name=subTitle,proto3" json:"subTitle"`
	Banner              string                 `protobuf:"bytes,4,opt,name=banner,proto3" json:"banner"`
	Info                string                 `protobuf:"bytes,5,opt,name=info,proto3" json:"info"`
	PeopleNum           int64                  `protobuf:"varint,6,opt,name=peopleNum,proto3" json:"peopleNum"`                      //容纳人的数量
	HomestayBusinessId  int64                  `protobuf:"varint,7,opt,name=homestayBusinessId,proto3" json:"homestayBusinessId"`    //店铺id
	UserId              int64                  `protobuf:"varint,8,opt,name=userId,proto3" json:"userId"`                            //房东id
	RowState            int64                  `protobuf:"varint,9,opt,name=rowState,proto3" json:"rowState"`                        //0:下架 1:上架
	RowType             int64                  `protobuf:"varint,10,opt,name=rowType,proto3" json:"rowType"`                         //售卖类型0：按房间出售 1:按人次出售
	FoodInfo            string                 `protobuf:"bytes,11,opt,name=foodInfo,proto3" json:"foodInfo"`                        //餐食标准
	FoodPrice           int64                  `protobuf:"varint,12,opt,name=foodPrice,proto3" json:"foodPrice"`                     //餐食价格(分)
	HomestayPrice       int64                  `protobuf:"varint,13,opt,name=homestayPrice,proto3" json:"homestayPrice"`             //民宿价格(分)
	MarketHomestayPrice int64                  `protobuf:"varint,14,opt,name=marketHomestayPrice,proto3" json:"marketHomestayPrice"` //民宿市场价格(分)
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Homestay) Reset() {
	*x = Homestay{}
	mi := &file_travel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Homestay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Homestay) ProtoMessage() {}

func (x *Homestay) ProtoReflect() protoreflect.Message {
	mi := &file_travel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Homestay.ProtoReflect.Descriptor instead.
func (*Homestay) Descriptor() ([]byte, []int) {
	return file_travel_proto_rawDescGZIP(), []int{0}
}

func (x *Homestay) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Homestay) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Homestay) GetSubTitle() string {
	if x != nil {
		return x.SubTitle
	}
	return ""
}

func (x *Homestay) GetBanner() string {
	if x != nil {
		return x.Banner
	}
	return ""
}

func (x *Homestay) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

func (x *Homestay) GetPeopleNum() int64 {
	if x != nil {
		return x.PeopleNum
	}
	return 0
}

func (x *Homestay) GetHomestayBusinessId() int64 {
	if x != nil {
		return x.HomestayBusinessId
	}
	return 0
}

func (x *Homestay) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Homestay) GetRowState() int64 {
	if x != nil {
		return x.RowState
	}
	return 0
}

func (x *Homestay) GetRowType() int64 {
	if x != nil {
		return x.RowType
	}
	return 0
}

func (x *Homestay) GetFoodInfo() string {
	if x != nil {
		return x.FoodInfo
	}
	return ""
}

func (x *Homestay) GetFoodPrice() int64 {
	if x != nil {
		return x.FoodPrice
	}
	return 0
}

func (x *Homestay) GetHomestayPrice() int64 {
	if x != nil {
		return x.HomestayPrice
	}
	return 0
}

func (x *Homestay) GetMarketHomestayPrice() int64 {
	if x != nil {
		return x.MarketHomestayPrice
	}
	return 0
}

type HomestayDetailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HomestayDetailReq) Reset() {
	*x = HomestayDetailReq{}
	mi := &file_travel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HomestayDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HomestayDetailReq) ProtoMessage() {}

func (x *HomestayDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_travel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HomestayDetailReq.ProtoReflect.Descriptor instead.
func (*HomestayDetailReq) Descriptor() ([]byte, []int) {
	return file_travel_proto_rawDescGZIP(), []int{1}
}

func (x *HomestayDetailReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type HomestayDetailResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Homestay      *Homestay              `protobuf:"bytes,1,opt,name=homestay,proto3" json:"homestay"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HomestayDetailResp) Reset() {
	*x = HomestayDetailResp{}
	mi := &file_travel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HomestayDetailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HomestayDetailResp) ProtoMessage() {}

func (x *HomestayDetailResp) ProtoReflect() protoreflect.Message {
	mi := &file_travel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HomestayDetailResp.ProtoReflect.Descriptor instead.
func (*HomestayDetailResp) Descriptor() ([]byte, []int) {
	return file_travel_proto_rawDescGZIP(), []int{2}
}

func (x *HomestayDetailResp) GetHomestay() *Homestay {
	if x != nil {
		return x.Homestay
	}
	return nil
}

var File_travel_proto protoreflect.FileDescriptor

const file_travel_proto_rawDesc = "" +
	"\n" +
	"\ftravel.proto\x12\x02pb\"\xa6\x03\n" +
	"\bHomestay\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1a\n" +
	"\bsubTitle\x18\x03 \x01(\tR\bsubTitle\x12\x16\n" +
	"\x06banner\x18\x04 \x01(\tR\x06banner\x12\x12\n" +
	"\x04info\x18\x05 \x01(\tR\x04info\x12\x1c\n" +
	"\tpeopleNum\x18\x06 \x01(\x03R\tpeopleNum\x12.\n" +
	"\x12homestayBusinessId\x18\a \x01(\x03R\x12homestayBusinessId\x12\x16\n" +
	"\x06userId\x18\b \x01(\x03R\x06userId\x12\x1a\n" +
	"\browState\x18\t \x01(\x03R\browState\x12\x18\n" +
	"\arowType\x18\n" +
	" \x01(\x03R\arowType\x12\x1a\n" +
	"\bfoodInfo\x18\v \x01(\tR\bfoodInfo\x12\x1c\n" +
	"\tfoodPrice\x18\f \x01(\x03R\tfoodPrice\x12$\n" +
	"\rhomestayPrice\x18\r \x01(\x03R\rhomestayPrice\x120\n" +
	"\x13marketHomestayPrice\x18\x0e \x01(\x03R\x13marketHomestayPrice\"#\n" +
	"\x11HomestayDetailReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\">\n" +
	"\x12HomestayDetailResp\x12(\n" +
	"\bhomestay\x18\x01 \x01(\v2\f.pb.HomestayR\bhomestay2I\n" +
	"\x06travel\x12?\n" +
	"\x0ehomestayDetail\x12\x15.pb.HomestayDetailReq\x1a\x16.pb.HomestayDetailRespB\x06Z\x04./pbb\x06proto3"

var (
	file_travel_proto_rawDescOnce sync.Once
	file_travel_proto_rawDescData []byte
)

func file_travel_proto_rawDescGZIP() []byte {
	file_travel_proto_rawDescOnce.Do(func() {
		file_travel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_travel_proto_rawDesc), len(file_travel_proto_rawDesc)))
	})
	return file_travel_proto_rawDescData
}

var file_travel_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_travel_proto_goTypes = []any{
	(*Homestay)(nil),           // 0: pb.Homestay
	(*HomestayDetailReq)(nil),  // 1: pb.HomestayDetailReq
	(*HomestayDetailResp)(nil), // 2: pb.HomestayDetailResp
}
var file_travel_proto_depIdxs = []int32{
	0, // 0: pb.HomestayDetailResp.homestay:type_name -> pb.Homestay
	1, // 1: pb.travel.homestayDetail:input_type -> pb.HomestayDetailReq
	2, // 2: pb.travel.homestayDetail:output_type -> pb.HomestayDetailResp
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_travel_proto_init() }
func file_travel_proto_init() {
	if File_travel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_travel_proto_rawDesc), len(file_travel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_travel_proto_goTypes,
		DependencyIndexes: file_travel_proto_depIdxs,
		MessageInfos:      file_travel_proto_msgTypes,
	}.Build()
	File_travel_proto = out.File
	file_travel_proto_goTypes = nil
	file_travel_proto_depIdxs = nil
}
