// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package handler

import (
	"net/http"

	HomestayOrder "study-zero/app/order/cmd/api/internal/handler/HomestayOrder"
	"study-zero/app/order/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// create homestay order
				Method:  http.MethodPost,
				Path:    "/homestayOrder/createHomestayOrder",
				Handler: HomestayOrder.CreateHomestayOrderHandler(serverCtx),
			},
			{
				// user homestay order detail
				Method:  http.MethodPost,
				Path:    "/homestayOrder/userHomestayOrderDetail",
				Handler: HomestayOrder.UserHomestayOrderDetailHandler(serverCtx),
			},
			{
				// user homestay order list
				Method:  http.MethodPost,
				Path:    "/homestayOrder/userHomestayOrderList",
				Handler: HomestayOrder.UserHomestayOrderListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/order/v1"),
	)
}
